package me.kitt3120.josu.enums;

public enum Mod {

	NONE, NOFAIL, EASY, NOVIDEO, HIDDEN, HARDROCK, SUDDENDEATH, DOUBLETIME, RELAX, HALFTIME, NIGHTCORE, FLASHLIGHT, AUTOPLAY, SPUNOUT, RELAX2, PERFECT, KEY4, KEY5, KEY6, KEY7, KEY8, KEYMOD, FADEIN, RANDOM, LASTMOD, KEY9, KEY10, KEY1, KEY3, KEY2;

}
